name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: dotnet test
      id: dotnet-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: dotnet test
        setup-command: ''
        command: DOTNET_CLI_HOME=/tmp/ dotnet test GameLibraryTests
        timeout: 3
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DOTNET-TEST_RESULTS: "${{steps.dotnet-test.outputs.result}}"
      with:
        runners: dotnet-test
